name: CommentReporting

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: Install DFX
        run: echo -e "yes" | DFX_VERSION=0.15.0 sh -c "$(curl -fsSL https://sdk.dfinity.org/install.sh)"

      - name: Start DFX background
        run: dfx start --background

      - name: Set up dfx identity
        run: |
          rm -f ~/.config/dfx/identity/sns_uat/identity.pem
          mkdir -p ~/.config/dfx/identity/sns_uat/
          echo "$SNS_UAT_IDENT" | base64 --decode > ~/.config/dfx/identity/sns_uat/identity.pem
          echo "$SNS_UAT_WALLET" > ~/.config/dfx/identity/sns_uat/wallets.json
          dfx identity use sns_uat
          dfx identity get-principal
          dfx identity set-wallet vf5cm-vaaaa-aaaak-qcqgq-cai --network ic
        env:
          SNS_UAT_IDENT: ${{ secrets.SNS_UAT_IDENT }}
          SNS_UAT_WALLET: ${{ secrets.SNS_UAT_WALLET }}

      - name: Get Principal
        run: dfx identity get-principal

      - name: Generate canister_ids.json and canisterIds.mo
        run: |
          mkdir -p ./.dfx/local && touch ./.dfx/local/canister_ids.json
          echo '{}' > ./.dfx/local/canister_ids.json
  
          echo '{
            "PostCore": { "ic": "'"$POSTCORE"'" },
            "PostBucket": { "ic": "'"$POSTBUCKET"'" }
          }' > canister_ids.json

        env:
          POSTCORE: ${{ secrets.SNS_UAT_POST_CORE }}
          POSTBUCKET: ${{ secrets.SNS_UAT_POST_BUCKET }}

      - name: Report Comments to Slack
        run: |
          echo "Fetching buckets..."
          BUCKETS_RAW=$(dfx canister call --network ic PostCore getAllBuckets --candid src/declarations/PostBucket/PostBucket.did -qq)
          BUCKETS=$(echo "$BUCKETS_RAW" | grep -oE '[a-z0-9]{5}-[a-z0-9]{5}-[a-z0-9]{5}-[a-z0-9]{5}-[a-z0-9]{3}' || echo '')
          echo "Buckets: $BUCKETS"
      
          SLACK_PAYLOAD='{"text":"*Comments Pending Review:*\n'
          for BUCKET in $BUCKETS
          do
            COMMENT_IDS_RAW=$(dfx canister call --network ic $BUCKET getReportedCommentIds --candid src/declarations/PostBucket/PostBucket.did -qq)
            COMMENT_IDS=$(echo "$COMMENT_IDS_RAW" | grep -oP 'vec \*\*\* "[^"]+"' | grep -oP '"\K[^"]+')
            echo "Comment IDs for bucket $BUCKET: $COMMENT_IDS"
      
            for ID in $COMMENT_IDS; do
              ARGUMENT='("'$ID'")'
              COMMENT_DETAIL=$(dfx canister call --network ic $BUCKET getComment $ARGUMENT --candid src/declarations/PostBucket/PostBucket.did -qq || echo '')
              COMMENT_CONTENT=$(echo "$COMMENT_DETAIL" | grep -oP 'content = "\K[^"]+')
              SLACK_PAYLOAD+="Comment ID: $ID, Content: $COMMENT_CONTENT\n"
            done
          done
          SLACK_PAYLOAD+='"}'
          echo "Sending the following payload to Slack:"
          echo "$SLACK_PAYLOAD"
          curl -X POST -H 'Content-type: application/json' --data "$SLACK_PAYLOAD" ${{ secrets.COMMENT_BOT_WEBHOOK }}
        env:
          COMMENT_BOT_WEBHOOK: ${{ secrets.COMMENT_BOT_WEBHOOK }}



      #     BALANCE=$(dfx canister --network ic call CyclesDispenser getStatus -qq | tr -d '\r\n"')
      #     echo "CYCLES_BALANCE=$BALANCE" >> $GITHUB_ENV
      # - name: Notify Slack
      #   run: |
      #     CURRENT_HOUR=$(date +"%H")
      #     SLACK_WEBHOOK_URL="https://hooks.slack.com/services/${{ secrets.SLACK_WEBHOOK_KEY }}"
      #     MESSAGE="Cycles Dispenser Status: ${{ env.CYCLES_BALANCE }}"
      #     MESSAGE_CLEANED=$(echo "$MESSAGE" | sed 's/[(),]//g')
      #     # Check if the message contains 'Everything is fine' and it's not the first hour of the day
      #     if [[ "$MESSAGE_CLEANED" != *"Everything is fine"* ]] || [[ "$CURRENT_HOUR" == "00" ]]; then
      #       curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"${MESSAGE_CLEANED}\"}" $SLACK_WEBHOOK_URL
      #     fi
