name: Deploy SNS UAT

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Debug SNS_UAT_IDENTITY
      run: echo "SNS_UAT_IDENTITY exists ${{ env.SNS_UAT_IDENT }}"
      env:
        SNS_UAT_IDENTITY: ${{ secrets.SNS_UAT_IDENT }}
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: npm install
      run: npm install

    - name: Install DFX
      run: echo -e "yes" | DFX_VERSION=0.15.0 sh -c "$(curl -fsSL https://sdk.dfinity.org/install.sh)"

    - name: Start DFX background
      run: dfx start --background

    - name: Set up dfx identity
      run: |
        rm -f ~/.config/dfx/identity/sns_uat/identity.pem
        mkdir -p ~/.config/dfx/identity/sns_uat/
        echo "$SNS_UAT_IDENT" | base64 --decode > ~/.config/dfx/identity/sns_uat/identity.pem
        echo "$SNS_UAT_WALLET" > ~/.config/dfx/identity/sns_uat/wallets.json
        dfx identity use sns_uat
        dfx identity get-principal
        dfx identity set-wallet vf5cm-vaaaa-aaaak-qcqgq-cai --network ic
      env:
        SNS_UAT_IDENT: ${{ secrets.SNS_UAT_IDENT }}
        SNS_UAT_WALLET: ${{ secrets.SNS_UAT_WALLET }}

          
    - name: Get Principal
      run:  dfx identity get-principal

    - name: Generate canister_ids.json in main repo
      run: |
        echo '{
          "FastBlocks_EmailOptIn": { "ic": "'"$FASTBLOCKS_EMAILOPTIN"'" },
          "KinicEndpoint": { "ic": "'"$KINICENDPOINT"'" },
          "CyclesDispenser": { "ic": "'"$CYCLESDISPENSER"'" },
          "PostIndex": { "ic": "'"$POSTINDEX"'" },
          "Storage": { "ic": "'"$STORAGE"'" },
          "User": { "ic": "'"$USER"'" },
          "nuance_assets": { "ic": "'"$NUANCE_ASSETS"'" },
          "PostCore": { "ic": "'"$POSTCORE"'" },
          "PostBucket": { "ic": "'"$POSTBUCKET"'" },
          "Metrics": { "ic": "'"$METRICS"'" }
        }' > canister_ids.json
      env:
        FASTBLOCKS_EMAILOPTIN: ${{ secrets.FASTBLOCKS_EMAILOPTIN }}
        KINICENDPOINT: ${{ secrets.KINICENDPOINT }}
        CYCLESDISPENSER: ${{ secrets.CYCLESDISPENSER }}
        POSTINDEX: ${{ secrets.POSTINDEX }}
        STORAGE: ${{ secrets.STORAGE }}
        USER: ${{ secrets.USER }}
        NUANCE_ASSETS: ${{ secrets.NUANCE_ASSETS }}
        POSTCORE: ${{ secrets.POSTCORE }}
        POSTBUCKET: ${{ secrets.POSTBUCKET }}
        METRICS: ${{ secrets.METRICS }}
        


      
    - name: Deploy local
      run: dfx deploy --network ic
