name: verify assets canister wasm hash

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: Install dfx
        uses: dfinity/setup-dfx@main
      - name: Confirm successful installation
        run: |
          dfxvm install 0.22.0
          dfxvm default 0.22.0
          dfx --version

      - name: Install Vessel
        run: |
          cd ./Nuance-NFTs-and-Publications
            wget https://github.com/dfinity/vessel/releases/download/v0.6.4/vessel-linux64
            mv vessel-linux64 vessel
            chmod +x vessel
            mv vessel /usr/local/bin/.
            vessel --version
          cd ..

      - name: Start DFX background
        run: dfx start --background

      - name: Create .env file
        run: |
          cat << EOF > .env
          II_PROVIDER_URL="https://identity.ic0.app/#authorize"
          II_PROVIDER_USE_FAKE="false"
          II_SESSION_TIMEOUT="480"
          II_INACTIVITY_TIMEOUT="480"
          UAT_FRONTEND_CANISTER_ID="${{ secrets.UAT_NUANCE_ASSETS }}"
          USERGEEK_API_KEY="${{ secrets.USERGEEK_API_KEY }}"
          USERGEEK_API_KEY_SECONDARY="${{ secrets.USERGEEK_API_KEY_SECONDARY }}"
          FASTBLOCKS_MAILERLITE_API_KEY="${{ secrets.FASTBLOCKS_MAILERLITE_API_KEY }}"
          DFX_NETWORK="ic"
          PUBLICATIONS_REPO_PATH=./Nuance-NFTs-and-Publications
          NUANCE_MAIN_REPO_PATH=./
          USER_CANISTER_ID = 'wlam3-raaaa-aaaap-qpmaa-cai'
          POST_CORE_CANISTER_ID = '4vm7k-tyaaa-aaaah-aq4wq-cai'
          KINIC_ENDPOINT_CANISTER_ID = 'sphnc-7yaaa-aaaao-a3wga-cai'
          FASTBLOCKS_EMAIL_OPT_IN_CANISTER_ID ='24qg5-ciaaa-aaaak-qtr7a-cai'
          POST_RELATIONS_CANISTER_ID = 'zjix6-iiaaa-aaaah-qpxca-cai'
          STORAGE_CANISTER_ID = '44puw-fqaaa-aaaah-aq4xa-cai'
          CYCLES_DISPENSER_CANISTER_ID = 'y6ydp-7aaaa-aaaaj-azwyq-cai'
          NUANCE_ASSETS_CANISTER_ID = 't6unq-pqaaa-aaaai-q3nqa-cai'
          METRICS_CANISTER_ID = 'a5asx-niaaa-aaaac-aacxq-cai'
          NFT_FACTORY_CANISTER_ID = 'kc4mb-myaaa-aaaaf-qajpq-cai'
          PUBLICATION_MANAGEMENT_CANISTER_ID = 'kq23y-aiaaa-aaaaf-qajmq-cai'
          NOTIFICATIONS_CANISTER_ID = 'z4pgt-jaaaa-aaaah-qpxbq-cai'
          SUBSCRIPTION_CANISTER_ID = 'yq2oh-eqaaa-aaaaj-azwzq-cai'
          EOF

      - name: Compute evidence for frontend canister
        run: |
          dfx canister create --all
          dfx build --all
          dfx generate
          dfx deploy nuance_assets --network ic --compute-evidence
