name: verify wasm hash for all (no frontend)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: Install dfx
        uses: dfinity/setup-dfx@main
      - name: Confirm successful installation
        run: |
          dfxvm install 0.22.0
          dfxvm default 0.22.0
          dfx --version

      - name: Install Vessel
        run: |
          cd ./Nuance-NFTs-and-Publications
            wget https://github.com/dfinity/vessel/releases/download/v0.6.4/vessel-linux64
            mv vessel-linux64 vessel
            chmod +x vessel
            mv vessel /usr/local/bin/.
            vessel --version
          cd ..

      - name: Start DFX background
        run: dfx start --background

      - name: Build all canisters
        run: |
          dfx canister create --all
          dfx build CyclesDispenser
          dfx build FastBlocks_EmailOptIn
          dfx build KinicEndpoint
          dfx build Metrics
          dfx build PostBucket
          dfx build PostCore
          dfx build PostRelations
          dfx build Storage
          dfx build User
          cd Nuance-NFTs-and-Publications
          dfx canister create --all
          dfx build PublicationManagement
          dfx build NftFactory
          dfx build Publisher

      - name: Get wasm hash for all
        run: |
          for canister in CyclesDispenser FastBlocks_EmailOptIn KinicEndpoint Metrics PostBucket PostCore PostRelations Storage User; do
            sha256sum .dfx/local/canisters/$canister/$canister.wasm
          done
          cd Nuance-NFTs-and-Publications
          for canister in PublicationManagement NftFactory Publisher; do
            sha256sum .dfx/local/canisters/$canister/$canister.wasm
          done
